### ISSUE TITLE
Check English grammar of readme file & make usage more clear

### ISSUE THREAD

**Issue by btk** [btk/codusic#3]
Hey, It would be really good if a native English speaker can check any typos or grammar mistakes possibly made in the readme file and documentation.

pull-requests are welcome.

**Comment by sameerkumar18** [comment]
Working on this.

**Comment by sameerkumar18** [comment]
I think it's already done #6

**Comment by s-Hale** [comment]
Corrected a few errors, PR sent.

**Comment by jenniferabowd** [comment]
@btk I am happy to further improve this once the other pull requests for this are approved.

**Comment by JoeScho** [comment]
I've added some updates in #12 which might be useful!

**Comment by btk** [comment]
Thank you all, @jenniferkaplannyc other pr's are reviewed. If you like to you can with the current master.

**Comment by btk** [comment]
Since there is no more improvements, I'm closing this issue, thank you everyone contributed.
