### ISSUE TITLE
Have a way to list most listened artists

### ISSUE THREAD

**Issue by btk** [btk/codusic#4]
Tool can ask if the the user wants to list the most listened tracks or artists, right after the time frame.

Most listened tracks are implemented, but we need to implement most listened tracks using lastfm api

**Comment by jainnidhi703** [comment]
Most listened tracks are implemented, but we need to implement most listened tracks using lastfm api, what do you mean by this?
You want to ask user to pick tracks/artist and then create the file?

**Comment by jainnidhi703** [comment]
Please take a look at https://github.com/btk/codusic/pull/13 for the above feature.

**Comment by btk** [comment]
My bad I meant "most listened artists" in the title. I just merged your feature. 

Thank you so much, closing this.
