### ISSUE TITLE
sget is deprecated

### ISSUE THREAD

**Issue by ypahalajani** [btk/codusic#9]
npm has deprecated sget. For more details, click [here](https://www.npmjs.com/package/sget)

**Comment by ypahalajani** [comment]
Please review PR #10

**Comment by ypahalajani** [comment]
@btk: Please review #10

**Comment by btk** [comment]
@ypahalajani thank you for noticing, read my reply on #10 please.

Thank you so much.

**Comment by ypahalajani** [comment]
@btk : I've update PR #10 . Please review it.

**Comment by btk** [comment]
Solved by #10, thank you so much.
